### ISSUE TITLE
Images are not linked with https

### ISSUE THREAD

**Issue by matpompili** [flagrow/image-upload#12]
Need to replace `http` with `https` it the images link

**Comment by Luceos** [comment]
Local images now stored as absolute paths: https://github.com/flagrow/image-upload/commit/17f0414c0c81f6135ed3d8c7ccfd42b7db713c97

**Comment by matpompili** [comment]
Imgur (oauth) links now served over https: https://github.com/flagrow/image-upload/commit/0e683df34d2703c3a2865d356391fa88f8b71d5a
